package com.novandi.premierleaguematchday.model

import com.novandi.premierleaguematchday.R

object ClubDataSource {
    val dummyMatchday = listOf(
        listOf(
            listOf("1", "Aston Villa", "H"),
            listOf("2", "Manchester City", "A"),
            listOf("3", "Arsenal", "H"),
            listOf("4", "Liverpool", "A"),
            listOf("5", "Wolverhampton Wanderers", "A")
        ),
        listOf(
            listOf("1", "Crystal Palace", "A"),
            listOf("2", "Leicester City", "H"),
            listOf("3", "Bournemouth", "A"),
            listOf("4", "Fulham", "H"),
            listOf("5", "Aston Villa", "H")
        ),
        listOf(
            listOf("1", "Bournemouth", "A"),
            listOf("2", "Everton", "H"),
            listOf("3", "Crystal Palace", "A"),
            listOf("4", "West Ham United", "H"),
            listOf("5", "Arsenal", "H")
        ),
        listOf(
            listOf("1", "Leicester City", "A"),
            listOf("2", "Manchester United", "H"),
            listOf("3", "Fulham", "A"),
            listOf("4", "Everton", "H"),
            listOf("5", "Crystal Palace", "A")
        ),
        listOf(
            listOf("1", "Manchester United", "A"),
            listOf("2", "Newcastle United", "H"),
            listOf("3", "West Ham United", "A"),
            listOf("4", "Leeds United", "H"),
            listOf("5", "Fulham", "A")
        ),
        listOf(
            listOf("1", "Everton", "A"),
            listOf("2", "Tottenham Hotspur", "H"),
            listOf("3", "Leeds United", "A"),
            listOf("4", "Leicester City", "H"),
            listOf("5", "Southampton", "A")
        ),
        listOf(
            listOf("1", "Arsenal", "H"),
            listOf("2", "Liverpool", "A"),
            listOf("3", "Aston Villa", "H"),
            listOf("4", "Manchester City", "A"),
            listOf("5", "Brentford", "H")
        ),
        listOf(
            listOf("1", "Chelsea", "H"),
            listOf("2", "Aston Villa", "A"),
            listOf("3", "Nottingham Forest", "H"),
            listOf("4", "Brentford", "A"),
            listOf("5", "Leeds United", "A")
        ),
        listOf(
            listOf("1", "Liverpool", "H"),
            listOf("2", "Wolverhampton Wanderers", "A"),
            listOf("3", "Brentford", "H"),
            listOf("4", "Arsenal", "A"),
            listOf("5", "Brighton & Hove Albion", "H")
        ),
        listOf(
            listOf("1", "Wolverhampton Wanderers", "H"),
            listOf("2", "Southampton", "A"),
            listOf("3", "Chelsea", "H"),
            listOf("4", "Brighton & Hove Albion", "A"),
            listOf("5", "Everton", "H")
        ),
        listOf(
            listOf("1", "Brentford", "H"),
            listOf("2", "Arsenal", "A"),
            listOf("3", "Southampton", "H"),
            listOf("4", "Chelsea", "A"),
            listOf("5", "Manchester United", "H")
        ),
        listOf(
            listOf("1", "Fulham", "A"),
            listOf("2", "Crystal Palace", "H"),
            listOf("3", "Manchester United", "A"),
            listOf("4", "Bournemouth", "H"),
            listOf("5", "Newcastle United", "H")
        ),
        listOf(
            listOf("1", "West Ham United", "A"),
            listOf("2", "Bournemouth", "H"),
            listOf("3", "Newcastle United", "A"),
            listOf("4", "Crystal Palace", "H"),
            listOf("5", "Nottingham Forest", "H")
        ),
        listOf(
            listOf("1", "Brighton & Hove Albion", "H"),
            listOf("2", "Brentford", "A"),
            listOf("3", "Liverpool", "H"),
            listOf("4", "Southampton", "A"),
            listOf("5", "Leicester City", "A")
        ),
        listOf(
            listOf("1", "Nottingham Forest", "H"),
            listOf("2", "Brighton & Hove Albion", "A"),
            listOf("3", "Manchester City", "H"),
            listOf("4", "Wolverhampton Wanderers", "A"),
            listOf("5", "Liverpool", "A"),
        ),
        listOf(
            listOf("1", "Newcastle United", "A"),
            listOf("2", "West Ham United", "H"),
            listOf("3", "Everton", "A"),
            listOf("4", "Tottenham Hotspur", "H"),
            listOf("5", "Manchester City", "A")
        ),
        listOf(
            listOf("1", "Tottenham Hotspur", "A"),
            listOf("2", "Leeds United", "H"),
            listOf("3", "Leicester City", "A"),
            listOf("4", "Manchester United", "H"),
            listOf("5", "Chelsea", "H")
        ),
        listOf(
            listOf("1", "Southampton", "H"),
            listOf("2", "Chelsea", "A"),
            listOf("3", "Wolverhampton Wanderers", "H"),
            listOf("4", "Nottingham Forest", "A"),
            listOf("5", "West Ham United", "A")
        ),
        listOf(
            listOf("1", "Manchester City", "H"),
            listOf("2", "Nottingham Forest", "A"),
            listOf("3", "Brighton & Hove Albion", "H"),
            listOf("4", "Aston Villa", "A"),
            listOf("5", "Tottenham Hotspur", "H")
        ),
        listOf(
            listOf("1", "Leeds United", "A"),
            listOf("2", "Fulham", "H"),
            listOf("3", "Tottenham Hotspur", "A"),
            listOf("4", "Newcastle United", "H"),
            listOf("5", "Bournemouth", "A")
        ),
    )
    val squadClubs = listOf(
        Squad(clubId = 1, squad = listOf(
            "Mark Travers",
            "Lloyd Kelly",
            "Chris Mepham",
            "Adam Smith",
            "Marcos Senesi",
            "Lewis Cook",
            "Jefferson Lerma",
            "Ryan Christie",
            "Jaidon Anthony",
            "Dominic Solanke",
            "Philip Billing",
            "Cameron Plain",
            "Jack Stephens",
            "Jack Stacey",
            "Jordan Zemura",
            "Joe Rothwell",
            "Siriki Dembélé",
            "Ben Pearson",
            "Jamal Lowe",
            "Kieffer Moore"
        )),
        Squad(clubId = 2, squad = listOf(
            "Aaron Ramsdale",
            "Ben White",
            "Gabriel Magalhães",
            "William Saliba",
            "Oleksandr Zinchenko",
            "Thomas Partey",
            "Martin Ødegaard",
            "Granit Xhaka",
            "Bukayo Saka",
            "Gabriel Martinelli",
            "Eddie Nketiah",
            "Matt Turner",
            "Kieran Tierney",
            "Rob Holding",
            "Cédric Soares",
            "Takehiro Tomiyasu",
            "Fábio Vieira",
            "Albert Sambi Lokonga",
            "Mohamed Elneny",
            "Marquinhos"
        )),
        Squad(clubId = 3, squad = listOf(
            "Robin Olsen",
            "Ezri Konsa",
            "Tyrone Mings",
            "Ashley Young",
            "Lucas Digne",
            "Douglas Luiz",
            "John McGinn",
            "Emiliano Buendía",
            "Boubacar Kamara",
            "Ollie Watkins",
            "Leon Bailey",
            "Emiliano Martínez",
            "Matty Cash",
            "Calum Chambers",
            "Ludwig Augustinsson",
            "Jan Bednarek",
            "Morgan Sanson",
            "Philippe Coutinho",
            "Danny Ings",
            "Cameron Archer"
        )),
        Squad(clubId = 4, squad = listOf(
            "David Raya",
            "Aaron Hickey",
            "Rico Henry",
            "Ethan Pinnock",
            "Ben Mee",
            "Christian Nørgaard",
            "Mathias Jensen",
            "Josh Dasilva",
            "Yoane Wissa",
            "Ivan Toney",
            "Bryan Mbeumo",
            "Matthew Cox",
            "Zanka",
            "Kristoffer Ajer",
            "Mads Roerslev",
            "Kevin Schade",
            "Mikkel Damsgaard",
            "Vitaly Janelt",
            "Saman Ghoddos",
            "Keane Lewis-Potter"
        )),
        Squad(clubId = 5, squad = listOf(
            "Robert Sánchez",
            "Lewis Dunk",
            "Pascal Groß",
            "Jan Paul van Hecke",
            "Pervis Estupiñán",
            "Solly March",
            "Alexis Mac Allister",
            "Adam Lallana",
            "Kaoru Mitoma",
            "Moisés Caicedo",
            "Danny Welbeck",
            "Jason Steele",
            "Tariq Lamptey",
            "Adam Webster",
            "Joël Veltman",
            "Billy Gilmour",
            "Jeremy Sarmiento",
            "Julio Enciso",
            "Deniz Undav",
            "Evan Ferguson"
        )),
        Squad(clubId = 6, squad = listOf(
            "Kepa Arrizabalaga",
            "Thiago Silva",
            "Kalidou Koulibaly",
            "César Azpilicueta",
            "Marc Cucurella",
            "Jorginho",
            "Mason Mount",
            "Denis Zakaria",
            "Christian Pulisic",
            "Raheem Sterling",
            "Kai Havertz",
            "Marcus Bettinelli",
            "Trevoh Chalobah",
            "Mateo Kovacic",
            "Hakim Ziyech",
            "Conor Gallagher",
            "Carney Chukwuemeka",
            "Omari Hutchinson",
            "Lewis Hall",
            "Pierre-Emerick Aubameyang"
        )),
        Squad(clubId = 7, squad = listOf(
            "Vicente Guaita",
            "Joel Ward",
            "Marc Guéhi",
            "Joachim Andersen",
            "Nathaniel Clyne",
            "Michael Olise",
            "Eberechi Eze",
            "Wilfried Zaha",
            "Jeffrey Schlupp",
            "Cheick Oumar Doucouré",
            "Jordan Ayew",
            "Jack Butland",
            "Chris Richards",
            "Will Hughes",
            "Malcolm Ebiowei",
            "Jairo Riedewald",
            "David Ozoh",
            "Jean-Philippe Mateta",
            "Odsonne Édouard",
            "John-Kymani Gordon"
        )),
        Squad(clubId = 8, squad = listOf(
            "Jordan Pickford",
            "James Tarkowski",
            "Nathan Patterson",
            "Vitaliy Mykolenko",
            "Ben Godfrey",
            "Conor Coady",
            "Amadou Onana",
            "Alex Iwobi",
            "Idrissa Gueye",
            "Dominic Calvert-Lewin",
            "Demarai Gray",
            "Asmir Begovic",
            "Mason Holgate",
            "Séamus Coleman",
            "Rúben Vinagre",
            "Abdoulaye Doucouré",
            "Tom Davies",
            "Isaac Price",
            "Dwight McNeil",
            "Neal Maupay"
        )),
        Squad(clubId = 9, squad = listOf(
            "Bernd Leno",
            "Kenny Tete",
            "Tim Ream",
            "Issa Diop",
            "Antonee Robinson",
            "Harrison Reed",
            "Bobby De Cordova-Reid",
            "Andreas Pereira",
            "Willian",
            "João Palhinha",
            "Aleksandar Mitrovic",
            "Marek Rodák",
            "Tosin Adarabioyo",
            "Shane Duffy",
            "Harry Wilson",
            "Tom Cairney",
            "Nathaniel Chalobah",
            "Dan James",
            "Luke Harris",
            "Carlos Vinícius"
        )),
        Squad(clubId = 10, squad = listOf(
            "Illan Meslier",
            "Robin Koch",
            "Liam Cooper",
            "Pascal Struijk",
            "Rasmus Kristensen",
            "Brenden Aaronson",
            "Marc Roca",
            "Crysencio Summerville",
            "Tyler Adams",
            "Wilfried Gnonto",
            "Rodrigo",
            "Joel Robles",
            "Luke Ayling",
            "Junior Firpo",
            "Diego Llorente",
            "Darko Gyabi",
            "Sonny Perkins",
            "Joe Gelhardt",
            "Sam Greenwood",
            "Mateo Joseph"
        )),
        Squad(clubId = 11, squad = listOf(
            "Danny Ward",
            "Wout Faes",
            "Daniel Amartey",
            "Timothy Castagne",
            "Luke Thomas",
            "Harvey Barnes",
            "Youri Tielemans",
            "James Maddison",
            "Kiernan Dewsbury-Hall",
            "Boubakary Soumaré",
            "Patson Daka",
            "Daniel Iversen",
            "Jonny Evans",
            "Marc Albrighton",
            "Nampalys Mendy",
            "Wilfred Ndidi",
            "Dennis Praet",
            "Jamie Vardy",
            "Kelechi Iheanacho",
            "Ayoze Pérez"
        )),
        Squad(clubId = 12, squad = listOf(
            "Alisson",
            "Virgil van Dijk",
            "Ibrahima Konaté",
            "Andrew Robertson",
            "Trent Alexander-Arnold",
            "Fabinho",
            "Thiago",
            "Roberto Firmino",
            "Harvey Elliott",
            "Mohamed Salah",
            "Darwin Núñez",
            "Caoimhín Kelleher",
            "Joe Gomez",
            "Konstantinos Tsimikas",
            "Calvin Ramsay",
            "Stefan Bajcetic",
            "Jordan Henderson",
            "Alex Oxlade-Chamberlain",
            "Curtis Jones",
            "Fábio Carvalho"
        )),
        Squad(clubId = 13, squad = listOf(
            "Ederson",
            "John Stones",
            "Nathan Aké",
            "João Cancelo",
            "Manuel Akanji",
            "Ilkay Gündogan",
            "Rodri",
            "Kevin De Bruyne",
            "Jack Grealish",
            "Julián Álvarez",
            "Bernardo Silva",
            "Stefan Ortega",
            "Rúben Dias",
            "Aymeric Laporte",
            "Rico Lewis",
            "Sergio Gómez",
            "Phil Foden",
            "Cole Palmer",
            "Erling Haaland",
            "Riyad Mahrez"
        )),
        Squad(clubId = 14, squad = listOf(
            "David de Gea",
            "Lisandro Martínez",
            "Raphaël Varane",
            "Diogo Dalot",
            "Luke Shaw",
            "Bruno Fernandes",
            "Christian Eriksen",
            "Casemiro",
            "Antony",
            "Jadon Sancho",
            "Marcus Rashford",
            "Tom Heaton",
            "Victor Lindelöf",
            "Tyrell Malacia",
            "Fred",
            "Facundo Pellistri",
            "Scott McTominay",
            "Alejandro Garnacho",
            "Zidane Iqbal",
            "Anthony Elanga"
        )),
        Squad(clubId = 15, squad = listOf(
            "Nick Pope",
            "Kieran Trippier",
            "Sven Botman",
            "Fabian Schär",
            "Dan Burn",
            "Joelinton",
            "Sean Longstaff",
            "Bruno Guimarães",
            "Callum Wilson",
            "Jacob Murphy",
            "Miguel Almirón",
            "Loris Karius",
            "Jamaal Lascelles",
            "Jamal Lewis",
            "Matt Targett",
            "Jonjo Shelvey",
            "Ryan Fraser",
            "Joe Willock",
            "Elliot Anderson",
            "Chris Wood"
        )),
        Squad(clubId = 16, squad = listOf(
            "Dean Henderson",
            "Steve Cook",
            "Neco Williams",
            "Serge Aurier",
            "Scott McKenna",
            "Orel Mangala",
            "Ryan Yates",
            "Remo Freuler",
            "Morgan Gibbs-White",
            "Jesse Lingard",
            "Brennan Johnson",
            "Wayne Hennessey",
            "Giulian Biancone",
            "Joe Worrall",
            "Harry Toffolo",
            "Willy Boly",
            "Cheikhou Kouyaté",
            "Taiwo Awoniyi",
            "Sam Surridge",
            "Emmanuel Dennis"
        )),
        Squad(clubId = 17, squad = listOf(
            "Gavin Bazunu",
            "Kyle Walker-Peters",
            "Romain Perraud",
            "Mohammed Salisu",
            "Armel Bella-Kotchap",
            "Ainsley Maitland-Niles",
            "James Ward-Prowse",
            "Mohamed Elyounoussi",
            "Joe Aribo",
            "Adam Armstrong",
            "Che Adams",
            "Alex McCarthy",
            "Lyanco",
            "Duje Caleta-Car",
            "Juan Larios",
            "Stuart Armstrong",
            "Moussa Djenepo",
            "Ibrahima Diallo",
            "Sékou Mara",
            "Samuel Edozie"
        )),
        Squad(clubId = 18, squad = listOf(
            "Hugo Lloris",
            "Eric Dier",
            "Cristian Romero",
            "Ben Davies",
            "Matt Doherty",
            "Pierre-Emile Højbjerg",
            "Ivan Perisic",
            "Rodrigo Bentancur",
            "Son Heung-Min",
            "Richarlison",
            "Harry Kane",
            "Fraser Forster",
            "Davinson Sánchez",
            "Djed Spence",
            "Clément Lenglet",
            "Oliver Skipp",
            "Ryan Sessegnon",
            "Yves Bissouma",
            "Bryan Gil",
            "Lucas Moura"
        )),
        Squad(clubId = 19, squad = listOf(
            "Lukasz Fabianski",
            "Aaron Cresswell",
            "Kurt Zouma",
            "Craig Dawson",
            "Thilo Kehrer",
            "Pablo Fornals",
            "Lucas Paquetá",
            "Jarrod Bowen",
            "Tomás Soucek",
            "Declan Rice",
            "Gianluca Scamacca",
            "Alphonse Aréola",
            "Ben Johnson",
            "Vladimír Coufal",
            "Angelo Ogbonna",
            "Emerson",
            "Manuel Lanzini",
            "Flynn Downes",
            "Michail Antonio",
            "Saïd Benrahma"
        )),
        Squad(clubId = 20, squad = listOf(
            "José Sá",
            "Jonny",
            "Nélson Semedo",
            "Maximilian Kilman",
            "Toti",
            "Daniel Podence",
            "Gonçalo Guedes",
            "Matheus Nunes",
            "João Moutinho",
            "Adama Traoré",
            "Diego Costa",
            "Matija Sarkic",
            "Rayan Aït-Nouri",
            "Yerson Mosquera",
            "Hugo Bueno",
            "Connor Ronan",
            "Joseph Hodge",
            "Chem Campbell",
            "Hwang Hee-Chan"
        ))
    )

    var dummyClubs = listOf(
        Club(1, "Bournemouth", "Vitality Stadium", "https://logodownload.org/wp-content/uploads/2019/10/bournemouth-fc-logo-3.png", R.color.bournemouth, squadClubs[0], dummyMatchday[0]),
        Club(2, "Arsenal", "Emirates Stadium", "https://assets.stickpng.com/images/580b57fcd9996e24bc43c4df.png", R.color.arsenal, squadClubs[1], dummyMatchday[1]),
        Club(3, "Aston Villa", "Villa Park", "https://upload.wikimedia.org/wikipedia/en/thumb/f/f9/Aston_Villa_FC_crest_%282016%29.svg/1200px-Aston_Villa_FC_crest_%282016%29.svg.png", R.color.astonvilla, squadClubs[2], dummyMatchday[2]),
        Club(4, "Brentford", "Gtech Community Stadium", "https://upload.wikimedia.org/wikipedia/id/thumb/2/2a/Brentford_FC_crest.svg/1200px-Brentford_FC_crest.svg.png", R.color.brenford, squadClubs[3], dummyMatchday[3]),
        Club(5, "Brighton & Hove Albion", "Amex Stadium", "https://logodownload.org/wp-content/uploads/2019/10/brighton-hove-albion-logo-1.png", R.color.brighton, squadClubs[4], dummyMatchday[4]),
        Club(6, "Chelsea", "Stamford Bridge", "https://assets.stickpng.com/images/580b57fcd9996e24bc43c4e1.png", R.color.chelsea, squadClubs[5], dummyMatchday[5]),
        Club(7, "Crystal Palace", "Selhurst Park", "https://upload.wikimedia.org/wikipedia/hif/c/c1/Crystal_Palace_FC_logo.png", R.color.crystalpalace, squadClubs[6], dummyMatchday[6]),
        Club(8, "Everton", "Goodison Park", "https://assets.stickpng.com/images/580b57fcd9996e24bc43c4e3.png", R.color.everton, squadClubs[7], dummyMatchday[7]),
        Club(9, "Fulham", "Craven Cottage", "https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Fulham_FC_%28shield%29.svg/1200px-Fulham_FC_%28shield%29.svg.png", R.color.fulham, squadClubs[8], dummyMatchday[8]),
        Club(10, "Leeds United", "Elland Road", "https://upload.wikimedia.org/wikipedia/en/thumb/5/54/Leeds_United_F.C._logo.svg/1200px-Leeds_United_F.C._logo.svg.png", R.color.leeds, squadClubs[9], dummyMatchday[9]),
        Club(11, "Leicester City", "King Power Stadium", "https://upload.wikimedia.org/wikipedia/hif/a/ab/Leicester_City_crest.png", R.color.leicester, squadClubs[10], dummyMatchday[10]),
        Club(12, "Liverpool", "Anfield", "https://assets.stickpng.com/images/580b57fcd9996e24bc43c4e5.png", R.color.liverpool, squadClubs[11], dummyMatchday[11]),
        Club(13, "Manchester City", "Etihad Stadium", "https://upload.wikimedia.org/wikipedia/en/thumb/e/eb/Manchester_City_FC_badge.svg/1200px-Manchester_City_FC_badge.svg.png", R.color.mancity, squadClubs[12], dummyMatchday[12]),
        Club(14, "Manchester United", "Old Trafford", "https://upload.wikimedia.org/wikipedia/id/thumb/7/7a/Manchester_United_FC_crest.svg/1200px-Manchester_United_FC_crest.svg.png", R.color.manunited, squadClubs[13], dummyMatchday[13]),
        Club(15, "Newcastle United", "St. James Park", "https://upload.wikimedia.org/wikipedia/en/thumb/5/56/Newcastle_United_Logo.svg/1200px-Newcastle_United_Logo.svg.png", R.color.newcastle, squadClubs[14], dummyMatchday[14]),
        Club(16, "Nottingham Forest", "The City Ground", "https://upload.wikimedia.org/wikipedia/en/thumb/e/e5/Nottingham_Forest_F.C._logo.svg/1200px-Nottingham_Forest_F.C._logo.svg.png", R.color.nottingham, squadClubs[15], dummyMatchday[15]),
        Club(17, "Southampton", "St. Mary's Stadium", "https://upload.wikimedia.org/wikipedia/id/thumb/c/c9/FC_Southampton.svg/1200px-FC_Southampton.svg.png", R.color.southampton, squadClubs[16], dummyMatchday[16]),
        Club(18, "Tottenham Hotspur", "Tottenham Hotspur Stadium", "https://upload.wikimedia.org/wikipedia/id/thumb/b/b4/Tottenham_Hotspur.svg/1200px-Tottenham_Hotspur.svg.png", R.color.tottenham, squadClubs[17], dummyMatchday[17]),
        Club(19, "West Ham United", "London Stadium", "https://upload.wikimedia.org/wikipedia/id/thumb/c/c2/West_Ham_United_FC_logo.svg/1200px-West_Ham_United_FC_logo.svg.png", R.color.westham, squadClubs[18], dummyMatchday[18]),
        Club(20, "Wolverhampton Wanderers", "Molineux Stadium", "https://upload.wikimedia.org/wikipedia/id/thumb/f/fc/Wolverhampton_Wanderers.svg/1200px-Wolverhampton_Wanderers.svg.png", R.color.wolves, squadClubs[19], dummyMatchday[19]),
    )
}